<?php
/**
 * ApiVersion200ResponseTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  DPInternetmarke\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Deutsche Post INTERNETMARKE API
 *
 * Division: Post & Parcel Germany<br /> The INTERNETMARKE is the online-postage for mail products of Deutsche Post AG.
 *
 * The version of the OpenAPI document: 1.30
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace DPInternetmarke\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ApiVersion200ResponseTest Class Doc Comment
 *
 * @category    Class
 * @description ApiVersion200Response
 * @package     DPInternetmarke\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ApiVersion200ResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ApiVersion200Response"
     */
    public function testApiVersion200Response()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "amp"
     */
    public function testPropertyAmp()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
