<?php
/**
 * VoucherTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  DPInternetmarke\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Deutsche Post INTERNETMARKE API
 *
 * Division: Post & Parcel Germany<br /> The INTERNETMARKE is the online-postage for mail products of Deutsche Post AG.
 *
 * The version of the OpenAPI document: 1.30
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace DPInternetmarke\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * VoucherTest Class Doc Comment
 *
 * @category    Class
 * @description The voucher encapsulates the voucher ID and the tracking ID.
 * @package     DPInternetmarke\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class VoucherTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Voucher"
     */
    public function testVoucher()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "voucher_id"
     */
    public function testPropertyVoucherId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "track_id"
     */
    public function testPropertyTrackId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
