<?php
/**
 * ApiVersionResourceApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  DPInternetmarke\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Deutsche Post INTERNETMARKE API
 *
 * Division: Post & Parcel Germany<br /> The INTERNETMARKE is the online-postage for mail products of Deutsche Post AG.
 *
 * The version of the OpenAPI document: 1.30
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace DPInternetmarke\Client\Test\Api;

use \DPInternetmarke\Client\Configuration;
use \DPInternetmarke\Client\ApiException;
use \DPInternetmarke\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ApiVersionResourceApiTest Class Doc Comment
 *
 * @category Class
 * @package  DPInternetmarke\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ApiVersionResourceApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiVersion
     *
     * Get information about this REST Api version..
     *
     */
    public function testApiVersion()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
