<?php
/**
 * AppResourceApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  DPInternetmarke\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Deutsche Post INTERNETMARKE API
 *
 * Division: Post & Parcel Germany<br /> The INTERNETMARKE is the online-postage for mail products of Deutsche Post AG.
 *
 * The version of the OpenAPI document: 1.30
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace DPInternetmarke\Client\Test\Api;

use \DPInternetmarke\Client\Configuration;
use \DPInternetmarke\Client\ApiException;
use \DPInternetmarke\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AppResourceApiTest Class Doc Comment
 *
 * @category Class
 * @package  DPInternetmarke\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AppResourceApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for chargeWallet
     *
     * Charge users wallet.
     *
     */
    public function testChargeWallet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for checkoutShoppingCartPDFApp
     *
     * Checkouts the PDF shopping cart. Be aware of the different types of schemas for checkout OR preview within the request. Preview does not need addresses..
     *
     */
    public function testCheckoutShoppingCartPDFApp()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for checkoutShoppingCartPNGApp
     *
     * Checkouts the PNG shopping cart. Be aware of the different types of schemas for checkout OR preview within the request. Preview does not need addresses. The print format is not relevant at this point..
     *
     */
    public function testCheckoutShoppingCartPNGApp()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for initShoppingCartApp
     *
     * Initializes a shopping cart and returns the shopOrderId..
     *
     */
    public function testInitShoppingCartApp()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for retoureVouchersApp
     *
     * Request retoure for ordered items corresponding to all items for shopOrderId or items with specific voucherId or trackId.
     *
     */
    public function testRetoureVouchersApp()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for retrieveCatalogApp
     *
     * Retrieve catalogs..
     *
     */
    public function testRetrieveCatalogApp()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for retrieveRetoureStateApp
     *
     * Retrieve retoure state for ordered items corresponding to shopRetoureId or retoureTransactionId.
     *
     */
    public function testRetrieveRetoureStateApp()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for retrieveShoppingCartApp
     *
     * Retrieves a shopping cart..
     *
     */
    public function testRetrieveShoppingCartApp()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
